version: "3.8"
services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=carrot
      - MYSQL_USER=local
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:alpine
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server --requirepass password --port 6379
    ports:
      - 6379:6379