spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrot?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: local
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false

  redis:
    host: localhost
    port: 6379
    password: password